---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  labels:
    name: bggapp-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: bggapp-pod
  strategy: # do a rolling update for question d.
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: bggapp-pod
      labels:
        name: bggapp-pod
    spec:
      containers:
      - name: bggapp-container
        #image: stackupiss/bgg-backend:v1
        image: stackupiss/bgg-backend:v2 # for upgrade
        imagePullPolicy: IfNotPresent
        ports:
        - name: bggapp-port
          containerPort: 3000
        envFrom:
        - configMapRef:
            name: bgg-cm
        - secretRef:
            name: mydb-secret
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          failureThreshold: 3
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels:
    name: bggapp-svc
spec:
  type: LoadBalancer
  selector:
    name: bggapp-pod
  ports:
  - port: 80
    targetPort: bggapp-port