---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgg-cm
  labels:
    name: bgg-cm
data:
  BGG_DB_USER: root
  BGG_DB_HOST: mydb-svc

---
apiVersion: v1
kind: Secret
metadata:
   name: mydb-secret
   labels:
      name: mydb-secret
data:
   BGG_DB_PASSWORD: Y2hhbmdlaXQ=