---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  labels:
    name: bggdb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bggdb-pod
  template:
    metadata: 
      name: bggdb-pod
      labels:
        name: bggdb-pod
    spec: 
      containers: 
      - name: bggdb-container
        image: stackupiss/bgg-database:v1
        ports:
        - name: bggdb-port
          containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mydb-svc
  labels:
    name: mydb-svc
spec:
  type: ClusterIP
  selector:
    name: bggdb-pod
  ports:
  - port: 3306
    targetPort: bggdb-port
  