---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wpdb-pvc
  labels:
    name: wpdb-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: wpdb-deploy
   labels:
      name: wpdb-deploy
spec:
   replicas: 1
   selector:
      matchLabels:
         name: wpdb-pod
   template:
      metadata:
         name: wpdb-pod
         labels:
            name: wpdb-pod
      spec:
         volumes:
         - name: wpdb-vol
           persistentVolumeClaim:
            claimName: wpdb-pvc
         containers:
         - name: wpdb-container
           image: mysql:5.6
           imagePullPolicy: IfNotPresent
           env:
           - name: MYSQL_ROOT_PASSWORD
             valueFrom:
              secretKeyRef:
                name: wpdb-secret
                key: ROOT_PASSWORD
           volumeMounts:
            - name: wpdb-vol
              mountPath: /var/lib/mysql
           ports: 
           - name: wpdb-host
             containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
   name: wpdb-svc
   labels:
      name: wpdb-svc
spec:
   type: ClusterIP
   selector:
      name: wpdb-pod
   ports:
   - port: 3306
     targetPort: wpdb-host